// Generated by gencpp from file rescue_pkg_noetic/AddTwoInts.msg
// DO NOT EDIT!


#ifndef RESCUE_PKG_NOETIC_MESSAGE_ADDTWOINTS_H
#define RESCUE_PKG_NOETIC_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <rescue_pkg_noetic/AddTwoIntsRequest.h>
#include <rescue_pkg_noetic/AddTwoIntsResponse.h>


namespace rescue_pkg_noetic
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace rescue_pkg_noetic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rescue_pkg_noetic::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::rescue_pkg_noetic::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::rescue_pkg_noetic::AddTwoInts > {
  static const char* value()
  {
    return "rescue_pkg_noetic/AddTwoInts";
  }

  static const char* value(const ::rescue_pkg_noetic::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rescue_pkg_noetic::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::rescue_pkg_noetic::AddTwoInts >
template<>
struct MD5Sum< ::rescue_pkg_noetic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rescue_pkg_noetic::AddTwoInts >::value();
  }
  static const char* value(const ::rescue_pkg_noetic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rescue_pkg_noetic::AddTwoIntsRequest> should match
// service_traits::DataType< ::rescue_pkg_noetic::AddTwoInts >
template<>
struct DataType< ::rescue_pkg_noetic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rescue_pkg_noetic::AddTwoInts >::value();
  }
  static const char* value(const ::rescue_pkg_noetic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rescue_pkg_noetic::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::rescue_pkg_noetic::AddTwoInts >
template<>
struct MD5Sum< ::rescue_pkg_noetic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rescue_pkg_noetic::AddTwoInts >::value();
  }
  static const char* value(const ::rescue_pkg_noetic::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rescue_pkg_noetic::AddTwoIntsResponse> should match
// service_traits::DataType< ::rescue_pkg_noetic::AddTwoInts >
template<>
struct DataType< ::rescue_pkg_noetic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rescue_pkg_noetic::AddTwoInts >::value();
  }
  static const char* value(const ::rescue_pkg_noetic::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RESCUE_PKG_NOETIC_MESSAGE_ADDTWOINTS_H
